# Generated by Django 3.1.7 on 2021-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210324_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='resimler/blog-2-1000x600.jpg', null=True, upload_to='resimler/'),
        ),
    ]
