# Generated by Django 3.1.7 on 2021-03-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210324_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='resimler/sean-o-KMn4VEeEPR8-unsplash.jpg', null=True, upload_to='resimler/'),
        ),
    ]
